### ISSUE TITLE
Make downsampling optional in quality metrics

### ISSUE THREAD

**Issue by nexplor** [francois-rozet/piqa#12]
#### Description
Right now, several metrics, like `MDSI`, `HaarPSI`, `VSI` etc., first downsample the image before calculating the distance (The downsampling is done by a fixed factor of 2 in HaarPSI, and to a size of at most 256 in MDSI and VSI. I didn't check the other modules, if they have something like this too).

This can cause problems if these are used as target losses for neural networks: for instance, if the network learns to add a chessboard-like-pattern (-1 if x+y is odd and 1 if it's even) to the image, the metric will not be changed at all, since the downsampled image hasn't been changed.

It's not just a theoretical problem, such patterns do arise in practice if the last layer is ConvTranspose2d.

#### Implementation

Add a kwarg `downsample=True` to these metrics (in both class and functional formats). It can have the default value of True to preserve backward compatibility. The images won't be downsampled if it is `False`.

#### Alternatives

None.

**Comment by francois-rozet** [comment]
The implementation is available in PR #13. I think it works, but I haven't had the time to test everything. Tell me if there is still an issue!
