### ISSUE TITLE
Option to disable type assertions

### ISSUE THREAD

**Issue by torridgristle** [francois-rozet/piqa#17]
#### Description

An argument to disable the use of `value_range`, the code that checks if the input tensors don't exceed 0-1 or 0-255. Or just disabling the entirety of `_assert_type`, I'm going to realize very quickly if my tensors are the wrong shape even without these and the only assert that's prone to go off suddenly is the `value_range` one.

The motivation is to enable the use of piqa for optimization, which often leads to values exceeding this range.

I recognize that metrics may cease to offer useful information if the values exceed the intended ranges, but other losses present during training may work well enough to bring it back into appropriate levels.

I've tried disabling asserts in Python via `!export PYTHONOPTIMIZE="True"` and variations thereof but it doesn't on Colab. I've tried `%env PYTHONOPTIMIZE="True"` and this allows me to run `!python -c "assert False"` without an assertion error, but piqa still gives assertion errors.

#### Implementation

An arg/kwarg like `self.skip_assert_value = kwargs.get('skip_assert_value', False)`
And in the forward pass for modules with asserts:
```
        _assert_type(
            [input, target],
            device=self.kernel.device,
            dim_range=(4, 4),
            n_channels=3,
            if self.skip_assert_value == False:
                value_range=(0., self.value_range),
        )
```

#### Alternatives

An alternate solution I've considered is just copying piqa and removing the asserts entirely so the asserts don't halt my training, but I can't be the only person with an interest in using piqa for training and this impacts anyone using piqa for training. I've also re-implemented SSIM on my own without the asserts and it seemed to work fine.

**Comment by francois-rozet** [comment]
Hello @torridgristle 👋 What would you say about an internal method `set_debug(mode)` that would disable `_assert_type` for the whole package ?

**Comment by torridgristle** [comment]
As long as I can set it within Colab, that sounds perfect.
