### ISSUE TITLE
JIT TypeError: Object of type 'module' is not an instance of 'function' with Python 3.9.1

### ISSUE THREAD

**Issue by trougnouf** [francois-rozet/piqa#6]
#### Description

I cannot build the package on Arch Linux with PyTorch 1.7.1 and Python 3.9 (using [aur](https://aur.archlinux.org/packages/python-pytorch-piqa-git/) , [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pytorch-piqa-git))

```
Traceback (most recent call last):
  File "/home/trougnouf/.cache/pacaur/python-pytorch-piqa-git/src/piqa/setup.py", line 5, in <module>
    import piqa
  File "/home/trougnouf/.cache/pacaur/python-pytorch-piqa-git/src/piqa/piqa/__init__.py", line 10, in <module>
    from .tv import TV
  File "/home/trougnouf/.cache/pacaur/python-pytorch-piqa-git/src/piqa/piqa/tv.py", line 16, in <module>
    def tv(x: torch.Tensor, norm: str = 'L1') -> torch.Tensor:
  File "/usr/lib/python3.9/site-packages/torch/jit/_script.py", line 939, in script
    fn = torch._C._jit_script_compile(
TypeError: Object of type 'module' is not an instance of 'function'
```

This may be a bug in PyTorch JIT, incompatibility with newer Numpy, or other, but I'm reporting here since this is the only place I've encountered the bug so far and I haven't seen another report.

#### Reproduce

On an up to date system:
```
git clone git@github.com:francois-rozet/piqa.git
cd piqa
python setup.py build
```
alternatively, with piqa succesfully built with older libraries and the system then updated, the same error is triggered with "import piqa"

#### Expected behavior

No error

#### Causes and solution

Workaround: set PIQA_JIT=0

#### Environment

* PIQA version: 5994e349d4c140877e560b18c2a51307e61575fc
* Python version: 3.9.1
* OS: Arch Linux
* Numpy 1.20
* PyTorch 1.7.1

**Comment by francois-rozet** [comment]
Hello @trougnouf 👋 Thank you for reporting this bug! Indeed, it seems to be a bug coming from the libraries as there is no object of type `module` in the functional definitions. I will try to narrow down the issue and report it to PyTorch.

You mention the package builds with older dependencies. If you remember, could you indicate what combinations of dependencies you tried ?

Anyway, I see only two possible fixes for the moment:
1. Limiting the dependencies to older ones
2. Disabling JIT by default (`PIQA_JIT=1` for activating)

I don't "like" either options, but I would say the latter is the less restricting for users. What do you think ?

**Comment by francois-rozet** [comment]
I have tested to upgrade my dependencies (`torch 1.7.1` and `numpy 1.20.0` ), but I couldn't reproduce the bug. However, I was unable to test with `Python 3.9.1` (I am limited to `3.9.0` on my machine), which is likely the source of error as `torch 1.7.1` was released for `3.9.0` and the JIT features are highly dependent on the interpreter (see [torch 1.7.1 release note](https://github.com/pytorch/pytorch/releases/tag/v1.7.1)).

Since it is not a problem of dependencies, I can only implement solution 2, *i.e.* disabling JIT by default.

**Comment by trougnouf** [comment]
Thank you for looking into it so promptly!
I saved the list of packages that got updated. They are as follow:
<details>
* acorn-1:8.0.5-1
* amdvlk-2021.Q1.2-1
* archlinux-appstream-data-20210125-1
* arm-none-eabi-newlib-4.1.0-1
* asciidoc-9.0.5-1
* brltty-6.2-4
* ca-certificates-mozilla-3.61-1
* certbot-1.11.0-2
* cmake-3.19.4-1
* ctags-1:r20210106+g08b1c490-1
* dialog-1:1.3_20210117-1
* dolphin-emu-1:5.0.r13495.caff472dbf-1
* electron-11.2.1-1
* electron9-9.4.2-1
* evince-3.38.1-1
* firefox-85.0-1
* flake8-1:3.8.4-4
* gd-2.3.1-1
* geoclue-2.5.7-2
* geoip-database-20210126-1
* glibmm-2.66.0-1
* gparted-1.2.0-2
* graphviz-2.46.0-1
* gst-editing-services-1.18.3-1
* hunspell-en_US-2020.12.07-1
* imagemagick-7.0.10.60-1
* inkscape-1.0.2-1
* intellij-idea-community-edition-4:2020.3.2-1
* iptables-1:1.8.7-1
* jasper-2.0.24-1
* js78-78.7.0-1
* kcompletion-5.78.0-2
* krb5-1.18.3-1
* lib32-gtk2-2.24.33-1
* lib32-libcap-2.47-1
* lib32-libgcrypt-1.9.1-1
* lib32-libgpg-error-1.41-1
* lib32-libva-2.10.0-1
* lib32-libxt-1.2.1-1
* lib32-nettle-3.7-1
* lib32-nss-3.61-1
* lib32-nvidia-utils-460.39-1
* lib32-opencl-nvidia-460.39-1
* lib32-pam-1.5.1-1
* lib32-pango-1:1.48.1-1
* lib32-sqlite-3.34.1-1
* libcap-2.47-1
* libgcrypt-1.9.1-1
* libical-3.0.9-1
* libinih-52-2
* libinstpatch-1.1.6-1
* libmbim-1.24.6-1
* librsvg-2:2.50.3-1
* libshout-1:2.4.5-1
* libtiff-4.2.0-1
* libwacom-1.8-1
* libxnvctrl-460.39-1
* libxt-1.2.1-1
* linux-5.10.11.arch1-1
* linux-headers-5.10.11.arch1-1
* linux-lts-5.4.93-2
* lua-penlight-1.9.2-1
* lua53-penlight-1.9.2-1
* luarocks-3.5.0-1
* mosquitto-2.0.5-1
* nextcloud-20.0.6-1
* node-gyp-7.1.2-1
* nodejs-lts-dubnium-10.23.2-1
* nss-3.61-1
* nvidia-460.39-2
* nvidia-lts-1:460.39-3
* nvidia-settings-460.39-1
* nvidia-utils-460.39-1
* opencl-nvidia-460.39-1
* pandoc-2.11.3-14
* pandoc-citeproc-0.17.0.2-163
* pango-1:1.48.1-1
* pangomm-2.46.0-1
* perl-image-exiftool-12.16-1
* perl-uri-5.06-1
* php-8.0.1-1
* php-apache-8.0.1-1
* php-apcu-5.1.19-2
* php-gd-8.0.1-1
* php-igbinary-3.2.1-2
* php-imagick-3.4.4.r66.g448c1cd-1
* php-intl-8.0.1-1
* php-pgsql-8.0.1-1
* php-redis-5.3.2-2
* php7-7.4.14-1
* php7-gd-7.4.14-1
* procps-ng-3.3.16-3
* pybind11-2.6.2-1
* python-acme-1.11.0-2
* python-bleach-3.2.2-1
* python-cachetools-4.2.1-1
* python-elementpath-2.1.2-1
* python-entrypoints-0.3-6
* python-grpcio-1.35.0-1
* python-importlib_resources-5.1.0-1
* python-josepy-1.6.0-1
* python-keras-applications-1.0.8-6
* python-keras-preprocessing-1.1.2-4
* python-keyring-22.0.1-1
* python-levenshtein-0.12.1-1
* python-mako-1.1.4-1
* python-matplotlib-3.3.4-1
* python-mccabe-0.6.1-8
* python-parse-1.19.0-1
* python-phonenumbers-8.12.17-1
* python-pip-20.3.1-1
* python-prompt_toolkit-3.0.14-1
* python-pyenchant-3.2.0-1
* python-pysaml2-6.5.1-1
* python-pytest-cov-2.11.1-1
* python-reportlab-3.5.60-1
* python-setuptools-1:52.0.0-1
* python-snowballstemmer-2.1.0-1
* python-sqlalchemy-1.3.22-1
* python-treq-21.1.0-1
* python-xmlschema-1.2.3-3
* python2-pip-20.3.1-1
* qbittorrent-4.3.3-1
* qt5-quick3d-5.15.2-2
* ruby-paint-2.2.1-1
* ruby-rdoc-6.3.0-1
* ruby-reline-0.2.2-1
* sbt-1:1.4.6-1
* sdl2_mixer-2.0.4-6
* serd-0.30.10-1
* smbclient-4.13.4-1
* spice-gtk-0.39-2
* sqlite-3.34.1-1
* sqlite-analyzer-3.34.1-1
* sshpass-1.08-1
* sudo-1.9.5.p2-1
* telepathy-glib-0.24.2-1
* tensorboard-2.4.1-1
* tt-rss-2:r10196.eb896f824-1
* tzdata-2021a-1
* vulkan-headers-1:1.2.168-1
* vulkan-html-docs-1:1.2.168-1
* wavpack-5.4.0-1
* wayland-1.19.0-1
* wireguard-lts-1.0.20210124-3
* wireshark-cli-3.4.3-1
* wireshark-qt-3.4.3-1
* xapian-core-1:1.4.18-1
* xf86-video-nouveau-1.0.17-1
* xorg-xwayland-1.20.0.r811.gf08ab719d-1
* youtube-dl-2021.01.24.1-1
* z3-4.8.10-1
</details>
Pytorch isn't in the list because I had to update it manually (the arch packager made a hiccup using numpy 1.20 which was still in the testing repo, it's in the main one now). It was updated from 1.7.1 with a cudnn 8.1 rebuild. Same with numpy (1.19 to 1.20).

Python isn't in the list, 3.9.1 must have been part of the previous update where I was using your stand-alone ms-ssim function from https://github.com/pytorch/pytorch/pull/22289#issuecomment-758958063 without issue.

The only thing I recognize as potentially relevant is pybind 2.6.1 -> 2.6.2
I wonder if this https://github.com/pytorch/pytorch/issues/51379 is relevant ? I found that when googling the error I got.

I think it may not be worth disabling JIT by default until the issue is confirmed on different distributions or we know what's causing it. If it's an easy `try except` it may be nice to give out the workaround PIQA_JIT=0 as a hint when the import fails.

**Comment by francois-rozet** [comment]
I have an idea of what could be causing the problem: the ellipsis operator `...`, which I only use in `piqa.tv.tv` (I think). It already caused some troubles when jumping from `3.8` to `3.9` (see https://github.com/pytorch/pytorch/issues/48674).

Could you try to remove the `tv` module and re-build/import ?
To do so:
1. Remove the file [tv.py](https://github.com/francois-rozet/piqa/blob/master/piqa/tv.py)
2. Remove the [import](https://github.com/francois-rozet/piqa/blob/master/piqa/__init__.py#L10) of `TV`

**Comment by trougnouf** [comment]
That didn't do it unfortunately.
```
[trougnouf@d]: ~/tmp/piqa>$ python setup.py build
Traceback (most recent call last):
  File "/orb/tmp/hometmp/piqa/setup.py", line 5, in <module>
    import piqa
  File "/orb/tmp/hometmp/piqa/piqa/__init__.py", line 11, in <module>
    from .psnr import PSNR
  File "/orb/tmp/hometmp/piqa/piqa/psnr.py", line 40, in <module>
    def psnr(
  File "/usr/lib/python3.9/site-packages/torch/jit/_script.py", line 939, in script
    fn = torch._C._jit_script_compile(
TypeError: Object of type 'module' is not an instance of 'function'
```
Importing the dummy file mentioned above doesn't return an error.

**Comment by francois-rozet** [comment]
Then I really don't know 😥 It seems to be linked to the classes rather than to the functionals like  https://github.com/pytorch/pytorch/issues/51379 suggests.

If I understood it correctly pybind11 is not necessary as it is already included in torch (?). If it is possible for you to remove it or downgrade it, could you try ?

**Comment by trougnouf** [comment]
Removing pybind seems tricky since the Arch packagers strip it during the pytorch package build, and I've failed to rebuild it myself so far.

I built and downgraded pybind 2.6.1, no success.

**Comment by trougnouf** [comment]
It's working with pytorch 1.8.0 and python 3.9.2 :)

I guess it'll be best to run with PIQA_JIT=1 since #7 .

Thank you!
